# Generated by Django 5.2.7 on 2025-10-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.CharField(blank=True, help_text='Departamento o categoría del proveedor (ej: Limpieza, Alimentos)', max_length=100, null=True),
        ),
    ]
